apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.referencencfs.configmapname }}
data:
  appsettings.json: |-
    {
      "UnprocessableFileTypeAction": "Relay",
      "GlasswallBlockedFilesAction": "Relay"
    } 