kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "reference-ncfs.fullname" . }}-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["update", "create", "get"] 